apiVersion: v1
kind: Service
metadata:
  name: service-spring-session
  namespace: sut
spec:  
  type: ClusterIP
  selector:
    key: spring-session-pod
  ports:
    - name: site
      protocol: TCP      
      port: 48100
      targetPort: 46801
